export const products = [
    { id: 1, name: 'Laptop', imageUrl: 'https://picsum.photos/id/0/200/300', price: 2000, category: 'Electronics', description: 'Powerful device' }, 
    { id: 2, name: 'T-shirt', imageUrl: 'https://picsum.photos/id/1/200/300', price: 50, category: 'Toys', description: 'Cotton T-shirt' }, 
    { id: 3, name: 'Book', imageUrl: 'https://picsum.photos/id/2/200/300', price: 25, category: 'Garden', description: 'Fiction novel' },
    { id: 4, name: 'Phone', imageUrl: 'https://picsum.photos/id/10/200/300', price: 1000, category: 'Beauty', description: 'Smartphone' },
    { id: 5, name: 'Jeans', imageUrl: 'https://picsum.photos/id/11/200/300', price: 80, category: 'Sports', description: 'Levi\'s jeans' },
    { id: 6, name: 'Cookbook', imageUrl: 'https://picsum.photos/id/12/200/300', price: 35, category: 'Home', description: 'Healthy recipes' },
    { id: 7, name: 'Headphones', imageUrl: 'https://picsum.photos/id/20/200/300', price: 150, category: 'Office', description: 'Noise-canceling headphones' },
    { id: 8, name: 'Dress', imageUrl: 'https://picsum.photos/id/21/200/300', price: 120, category: 'Automotive', description: 'Summer dress' },
    { id: 9, name: 'Mystery', imageUrl: 'https://picsum.photos/id/22/200/300', price: 28, category: 'Health', description: 'Thriller novel' },
    { id: 10, name: 'Smartwatch', imageUrl: 'https://picsum.photos/id/25/200/300', price: 300, category: 'Books', description: 'Fitness tracker' },
    { id: 11, name: 'Sneakers', imageUrl: 'https://picsum.photos/id/26/200/300', price: 100, category: 'Clothing', description: 'Running shoes' },
    { id: 12, name: 'Notebook', imageUrl: 'https://picsum.photos/id/27/200/300', price: 12, category: 'Electronics', description: 'Spiral notebook' },
    { id: 13, name: 'Tablet', imageUrl: 'https://picsum.photos/id/28/200/300', price: 450, category: 'Toys', description: '10-inch screen tablet' },
    { id: 14, name: 'Jacket', imageUrl: 'https://picsum.photos/id/29/200/300', price: 150, category: 'Beauty', description: 'Waterproof jacket' },
    { id: 15, name: 'Science Book', imageUrl: 'https://picsum.photos/id/30/200/300', price: 32, category: 'Garden', description: 'Intro to Physics' },
    { id: 16, name: 'Camera', imageUrl: 'https://picsum.photos/id/31/200/300', price: 800, category: 'Sports', description: 'DSLR Camera' },
    { id: 17, name: 'Sweater', imageUrl: 'https://picsum.photos/id/32/200/300', price: 60, category: 'Home', description: 'Wool sweater' },
    { id: 18, name: 'Biography', imageUrl: 'https://picsum.photos/id/33/200/300', price: 22, category: 'Office', description: 'Famous person biography' },
    { id: 19, name: 'Bluetooth Speaker', imageUrl: 'https://picsum.photos/id/34/200/300', price: 90, category: 'Automotive', description: 'Portable speaker' },
    { id: 20, name: 'Skirt', imageUrl: 'https://picsum.photos/id/35/200/300', price: 70, category: 'Health', description: 'Casual skirt' },
    { id: 21, name: 'Cookbook 2', imageUrl: 'https://picsum.photos/id/36/200/300', price: 38, category: 'Books', description: 'Quick recipes' },
    { id: 22, name: 'VR Headset', imageUrl: 'https://picsum.photos/id/37/200/300', price: 350, category: 'Clothing', description: 'Virtual reality set' },
    { id: 23, name: 'Dress Shirt', imageUrl: 'https://picsum.photos/id/38/200/300', price: 80, category: 'Electronics', description: 'Button-up shirt' },
    { id: 24, name: 'Classic Novel', imageUrl: 'https://picsum.photos/id/39/200/300', price: 18, category: 'Toys', description: 'Old classic tale' },
    { id: 25, name: 'E-reader', imageUrl: 'https://picsum.photos/id/40/200/300', price: 180, category: 'Beauty', description: 'Kindle-style device' },
    { id: 26, name: 'Joggers', imageUrl: 'https://picsum.photos/id/41/200/300', price: 58, category: 'Garden', description: 'Athletic joggers' },
    { id: 27, name: 'Travel Guide', imageUrl: 'https://picsum.photos/id/42/200/300', price: 34, category: 'Sports', description: 'Vacation guidebook' },
    { id: 28, name: 'Wireless Charger', imageUrl: 'https://picsum.photos/id/43/200/300', price: 40, category: 'Home', description: 'Qi charger pad' },
    { id: 29, name: 'Blazer', imageUrl: 'https://picsum.photos/id/44/200/300', price: 110, category: 'Office', description: 'Formal blazer' },
    { id: 30, name: 'Romance Book', imageUrl: 'https://picsum.photos/id/45/200/300', price: 17, category: 'Automotive', description: 'Romantic fiction' },
    { id: 31, name: 'MP3 Player', imageUrl: 'https://picsum.photos/id/46/200/300', price: 70, category: 'Health', description: 'Portable music player' },
    { id: 32, name: 'Tank Top', imageUrl: 'https://picsum.photos/id/47/200/300', price: 25, category: 'Books', description: 'Casual tank top' },
    { id: 33, name: 'History Book', imageUrl: 'https://picsum.photos/id/48/200/300', price: 30, category: 'Clothing', description: 'World history' },
    { id: 34, name: 'Smart TV', imageUrl: 'https://picsum.photos/id/49/200/300', price: 950, category: 'Electronics', description: '4K LED TV' },
    { id: 35, name: 'Shorts', imageUrl: 'https://picsum.photos/id/50/200/300', price: 35, category: 'Toys', description: 'Summer shorts' },
    { id: 36, name: 'Poetry Book', imageUrl: 'https://picsum.photos/id/51/200/300', price: 24, category: 'Beauty', description: 'Poetry collection' },
    { id: 37, name: 'Drone', imageUrl: 'https://picsum.photos/id/52/200/300', price: 400, category: 'Garden', description: 'Quadcopter drone' },
    { id: 38, name: 'Windbreaker', imageUrl: 'https://picsum.photos/id/53/200/300', price: 60, category: 'Sports', description: 'Light jacket' },
    { id: 39, name: 'Science Fiction', imageUrl: 'https://picsum.photos/id/54/200/300', price: 25, category: 'Home', description: 'Space adventures' },
    { id: 40, name: 'Wireless Mouse', imageUrl: 'https://picsum.photos/id/55/200/300', price: 45, category: 'Office', description: 'Bluetooth mouse' },
    { id: 41, name: 'Polo Shirt', imageUrl: 'https://picsum.photos/id/56/200/300', price: 55, category: 'Automotive', description: 'Polo style shirt' },
    { id: 42, name: 'Children\'s Book', imageUrl: 'https://picsum.photos/id/57/200/300', price: 15, category: 'Health', description: 'For young readers' },
    { id: 43, name: 'Fitness Band', imageUrl: 'https://picsum.photos/id/58/200/300', price: 80, category: 'Books', description: 'Activity tracker' },
    { id: 44, name: 'Skating Pants', imageUrl: 'https://picsum.photos/id/59/200/300', price: 65, category: 'Clothing', description: 'For skating' },
    { id: 45, name: 'Comic Book', imageUrl: 'https://picsum.photos/id/60/200/300', price: 12, category: 'Electronics', description: 'Graphic novel' },
    { id: 46, name: 'Smart Light', imageUrl: 'https://picsum.photos/id/61/200/300', price: 35, category: 'Toys', description: 'WiFi lightbulb' },
    { id: 47, name: 'Hoodie', imageUrl: 'https://picsum.photos/id/62/200/300', price: 75, category: 'Beauty', description: 'Comfy hoodie' },
    { id: 48, name: 'Language Guide', imageUrl: 'https://picsum.photos/id/63/200/300', price: 27, category: 'Garden', description: 'Learn languages' },
    { id: 49, name: 'Laptop Stand', imageUrl: 'https://picsum.photos/id/64/200/300', price: 55, category: 'Sports', description: 'Ergonomic stand' },
    { id: 50, name: 'Raincoat', imageUrl: 'https://picsum.photos/id/65/200/300', price: 99, category: 'Home', description: 'Rain protection' },
    { id: 51, name: 'Fantasy Book', imageUrl: 'https://picsum.photos/id/66/200/300', price: 29, category: 'Office', description: 'Magic worlds' },
    { id: 52, name: 'Streaming Stick', imageUrl: 'https://picsum.photos/id/67/200/300', price: 65, category: 'Automotive', description: 'Media streaming' },
    { id: 53, name: 'Vest', imageUrl: 'https://picsum.photos/id/68/200/300', price: 47, category: 'Health', description: 'Light vest' },
    { id: 54, name: 'Atlas', imageUrl: 'https://picsum.photos/id/69/200/300', price: 41, category: 'Books', description: 'World atlas' },
    { id: 55, name: 'Fitness Scale', imageUrl: 'https://picsum.photos/id/70/200/300', price: 75, category: 'Clothing', description: 'Smart scale' },
    { id: 56, name: 'Cap', imageUrl: 'https://picsum.photos/id/71/200/300', price: 22, category: 'Electronics', description: 'Baseball cap' },
    { id: 57, name: 'Guide Book', imageUrl: 'https://picsum.photos/id/72/200/300', price: 35, category: 'Toys', description: 'Tips and tricks' },
    { id: 58, name: 'Fitness Mat', imageUrl: 'https://picsum.photos/id/73/200/300', price: 38, category: 'Beauty', description: 'Yoga mat' },
    { id: 59, name: 'Leggings', imageUrl: 'https://picsum.photos/id/74/200/300', price: 44, category: 'Garden', description: 'Stretch leggings' },
    { id: 60, name: 'Horror Book', imageUrl: 'https://picsum.photos/id/75/200/300', price: 26, category: 'Sports', description: 'Scary stories' },
    { id: 61, name: 'Smart Thermostat', imageUrl: 'https://picsum.photos/id/76/200/300', price: 150, category: 'Home', description: 'WiFi thermostat' },
    { id: 62, name: 'Puffer Jacket', imageUrl: 'https://picsum.photos/id/77/200/300', price: 170, category: 'Office', description: 'Warm jacket' },
    { id: 63, name: 'Art Book', imageUrl: 'https://picsum.photos/id/78/200/300', price: 45, category: 'Automotive', description: 'Art collections' },
    { id: 64, name: 'Console', imageUrl: 'https://picsum.photos/id/79/200/300', price: 450, category: 'Health', description: 'Game console' },
    { id: 65, name: 'Overalls', imageUrl: 'https://picsum.photos/id/80/200/300', price: 85, category: 'Books', description: 'Classic overalls' },
    { id: 66, name: 'Puzzle Book', imageUrl: 'https://picsum.photos/id/81/200/300', price: 20, category: 'Clothing', description: 'Brain puzzles' },
    { id: 67, name: 'Noise Cancelling Earbuds', imageUrl: 'https://picsum.photos/id/82/200/300', price: 120, category: 'Electronics', description: 'In-ear headphones' },
    { id: 68, name: 'Cargo Pants', imageUrl: 'https://picsum.photos/id/83/200/300', price: 54, category: 'Toys', description: 'Multi-pocket pants' },
    { id: 69, name: 'Essay Book', imageUrl: 'https://picsum.photos/id/84/200/300', price: 28, category: 'Beauty', description: 'Essay collection' },
    { id: 70, name: 'Smart Plug', imageUrl: 'https://picsum.photos/id/85/200/300', price: 25, category: 'Garden', description: 'Pluggable device' },
    { id: 71, name: 'Cardigan', imageUrl: 'https://picsum.photos/id/86/200/300', price: 70, category: 'Sports', description: 'Open sweater' },
    { id: 72, name: 'Encyclopedia', imageUrl: 'https://picsum.photos/id/87/200/300', price: 55, category: 'Home', description: 'Reference book' },
    { id: 73, name: 'Robot Vacuum', imageUrl: 'https://picsum.photos/id/88/200/300', price: 250, category: 'Office', description: 'Automatic vacuum' },
    { id: 74, name: 'Denim Jacket', imageUrl: 'https://picsum.photos/id/89/200/300', price: 90, category: 'Automotive', description: 'Classic denim' },
    { id: 75, name: 'Dictionary', imageUrl: 'https://picsum.photos/id/90/200/300', price: 30, category: 'Health', description: 'Word meanings' },
    { id: 76, name: 'Action Camera', imageUrl: 'https://picsum.photos/id/91/200/300', price: 180, category: 'Books', description: 'Adventure camera' },
    { id: 77, name: 'Tracksuit', imageUrl: 'https://picsum.photos/id/92/200/300', price: 110, category: 'Clothing', description: 'Sports set' },
    { id: 78, name: 'Journal', imageUrl: 'https://picsum.photos/id/93/200/300', price: 21, category: 'Electronics', description: 'Lined notebook' },
    { id: 79, name: 'Projector', imageUrl: 'https://picsum.photos/id/94/200/300', price: 360, category: 'Toys', description: 'HD projector' },
    { id: 80, name: 'Cardigan 2', imageUrl: 'https://picsum.photos/id/95/200/300', price: 68, category: 'Beauty', description: 'Soft cardigan' },
    { id: 81, name: 'Biography 2', imageUrl: 'https://picsum.photos/id/96/200/300', price: 25, category: 'Garden', description: 'Leader\'s story' },
    { id: 82, name: 'Desktop PC', imageUrl: 'https://picsum.photos/id/97/200/300', price: 1200, category: 'Sports', description: 'Personal computer' },
    { id: 83, name: 'Anorak', imageUrl: 'https://picsum.photos/id/98/200/300', price: 130, category: 'Home', description: 'Weather-proof' },
    { id: 84, name: 'Classic Drama', imageUrl: 'https://picsum.photos/id/99/200/300', price: 34, category: 'Office', description: 'Play script' },
    { id: 85, name: 'Monitor', imageUrl: 'https://picsum.photos/id/100/200/300', price: 280, category: 'Automotive', description: '24-inch display' },
    { id: 86, name: 'Turtleneck', imageUrl: 'https://picsum.photos/id/101/200/300', price: 50, category: 'Health', description: 'Warm pullover' },
    { id: 87, name: 'Photography Book', imageUrl: 'https://picsum.photos/id/102/200/300', price: 40, category: 'Books', description: 'Photo collection' },
    { id: 88, name: 'Portable SSD', imageUrl: 'https://picsum.photos/id/103/200/300', price: 110, category: 'Clothing', description: 'Fast storage' },
    { id: 89, name: 'Gloves', imageUrl: 'https://picsum.photos/id/104/200/300', price: 32, category: 'Electronics', description: 'Winter gloves' },
    { id: 90, name: 'Children Stories', imageUrl: 'https://picsum.photos/id/105/200/300', price: 19, category: 'Toys', description: 'Stories for kids' },
    { id: 91, name: 'Fitness Watch', imageUrl: 'https://picsum.photos/id/106/200/300', price: 200, category: 'Beauty', description: 'Sports tracking' },
    { id: 92, name: 'Short Sleeve Shirt', imageUrl: 'https://picsum.photos/id/107/200/300', price: 37, category: 'Garden', description: 'For warm weather' },
    { id: 93, name: 'Guide to Cooking', imageUrl: 'https://picsum.photos/id/108/200/300', price: 29, category: 'Sports', description: 'Cooking basics' },
    { id: 94, name: 'Gaming Mouse', imageUrl: 'https://picsum.photos/id/109/200/300', price: 59, category: 'Home', description: 'Customizable mouse' },
    { id: 95, name: 'Yoga Pants', imageUrl: 'https://picsum.photos/id/110/200/300', price: 48, category: 'Office', description: 'Flexible fit' },
    { id: 96, name: 'Business Book', imageUrl: 'https://picsum.photos/id/111/200/300', price: 24, category: 'Automotive', description: 'Entrepreneurship' },
    { id: 97, name: 'Bluetooth Earphones', imageUrl: 'https://picsum.photos/id/112/200/300', price: 62, category: 'Health', description: 'Wireless audio' },
    { id: 98, name: 'Winter Coat', imageUrl: 'https://picsum.photos/id/113/200/300', price: 190, category: 'Books', description: 'Insulated coat' },
    { id: 99, name: 'Travel Diary', imageUrl: 'https://picsum.photos/id/114/200/300', price: 26, category: 'Clothing', description: 'Document travels' },
    { id: 100, name: 'Smart Lock', imageUrl: 'https://picsum.photos/id/115/200/300', price: 130, category: 'Electronics', description: 'Door lock system' },
    { id: 101, name: 'Board Shorts', imageUrl: 'https://picsum.photos/id/116/200/300', price: 36, category: 'Toys', description: 'For surfing' },
    { id: 102, name: 'Detective Story', imageUrl: 'https://picsum.photos/id/117/200/300', price: 21, category: 'Beauty', description: 'Crime mysteries' },
    { id: 103, name: 'Smart Scale', imageUrl: 'https://picsum.photos/id/118/200/300', price: 70, category: 'Garden', description: 'Weight tracking' },
    { id: 104, name: 'Socks', imageUrl: 'https://picsum.photos/id/119/200/300', price: 15, category: 'Sports', description: 'Cotton socks' },
    { id: 105, name: 'Cookbook 3', imageUrl: 'https://picsum.photos/id/120/200/300', price: 36, category: 'Home', description: 'Vegetarian recipes' },
    { id: 106, name: 'Headset', imageUrl: 'https://picsum.photos/id/121/200/300', price: 105, category: 'Office', description: 'Gaming headset' },
    { id: 107, name: 'Romper', imageUrl: 'https://picsum.photos/id/122/200/300', price: 65, category: 'Automotive', description: 'Casual romper' },
    { id: 108, name: 'Puzzle Collection', imageUrl: 'https://picsum.photos/id/123/200/300', price: 29, category: 'Health', description: 'Lots of puzzles' },
    { id: 109, name: 'Tablet Pen', imageUrl: 'https://picsum.photos/id/124/200/300', price: 39, category: 'Books', description: 'Stylus for tablet' },
    { id: 110, name: 'Rain Boots', imageUrl: 'https://picsum.photos/id/125/200/300', price: 53, category: 'Clothing', description: 'Waterproof boots' },
    { id: 111, name: 'Children\'s Science', imageUrl: 'https://picsum.photos/id/126/200/300', price: 17, category: 'Electronics', description: 'Science for kids' },
    { id: 112, name: 'Flash Drive', imageUrl: 'https://picsum.photos/id/127/200/300', price: 19, category: 'Toys', description: 'USB memory stick' },
    { id: 113, name: 'Sports Bra', imageUrl: 'https://picsum.photos/id/128/200/300', price: 32, category: 'Beauty', description: 'Athletic wear' },
    { id: 114, name: 'Short Stories', imageUrl: 'https://picsum.photos/id/129/200/300', price: 22, category: 'Garden', description: 'Short story collection' },
    { id: 115, name: 'Smart Camera', imageUrl: 'https://picsum.photos/id/130/200/300', price: 290, category: 'Sports', description: 'WiFi camera' },
    { id: 116, name: 'Crop Top', imageUrl: 'https://picsum.photos/id/131/200/300', price: 33, category: 'Home', description: 'Trendy crop top' },
    { id: 117, name: 'Children\'s Dictionary', imageUrl: 'https://picsum.photos/id/132/200/300', price: 14, category: 'Office', description: 'Words for kids' },
    { id: 118, name: 'Fitness Gloves', imageUrl: 'https://picsum.photos/id/133/200/300', price: 21, category: 'Automotive', description: 'Workout gloves' },
    { id: 119, name: 'Fleece Jacket', imageUrl: 'https://picsum.photos/id/134/200/300', price: 77, category: 'Health', description: 'Warm fleece' },
    { id: 120, name: 'Sports Stories', imageUrl: 'https://picsum.photos/id/135/200/300', price: 20, category: 'Books', description: 'Sports tales' },
    { id: 121, name: 'Keyboard', imageUrl: 'https://picsum.photos/id/136/200/300', price: 75, category: 'Clothing', description: 'Wireless keyboard' },
    { id: 122, name: 'Chinos', imageUrl: 'https://picsum.photos/id/137/200/300', price: 56, category: 'Electronics', description: 'Casual pants' },
    { id: 123, name: 'Comics for Kids', imageUrl: 'https://picsum.photos/id/138/200/300', price: 16, category: 'Toys', description: 'Comics for children' },
    { id: 124, name: 'Smart Kettle', imageUrl: 'https://picsum.photos/id/139/200/300', price: 85, category: 'Beauty', description: 'App controlled kettle' },
    { id: 125, name: 'Poncho', imageUrl: 'https://picsum.photos/id/140/200/300', price: 48, category: 'Garden', description: 'Waterproof poncho' },
    { id: 126, name: 'Nature Guide', imageUrl: 'https://picsum.photos/id/141/200/300', price: 37, category: 'Sports', description: 'Nature walk guide' },
    { id: 127, name: 'Action Cam', imageUrl: 'https://picsum.photos/id/142/200/300', price: 260, category: 'Home', description: 'Mini action camera' },
    { id: 128, name: 'Vest 2', imageUrl: 'https://picsum.photos/id/143/200/300', price: 41, category: 'Office', description: 'Warm vest' },
    { id: 129, name: 'Poetry Anthology', imageUrl: 'https://picsum.photos/id/144/200/300', price: 33, category: 'Automotive', description: 'Poetry from around the world' },
    { id: 130, name: 'Wi-Fi Router', imageUrl: 'https://picsum.photos/id/145/200/300', price: 130, category: 'Health', description: 'Wireless router' },
    { id: 131, name: 'Shawl', imageUrl: 'https://picsum.photos/id/146/200/300', price: 29, category: 'Books', description: 'Warm shawl' },
    { id: 132, name: 'Mythology Stories', imageUrl: 'https://picsum.photos/id/147/200/300', price: 18, category: 'Clothing', description: 'Ancient myths' },
    { id: 133, name: 'Bluetooth Adapter', imageUrl: 'https://picsum.photos/id/148/200/300', price: 27, category: 'Electronics', description: 'Adapter for PC' },
    { id: 134, name: 'Dungarees', imageUrl: 'https://picsum.photos/id/149/200/300', price: 66, category: 'Toys', description: 'Classic dungarees' },
    { id: 135, name: 'Encyclopedia of Science', imageUrl: 'https://picsum.photos/id/150/200/300', price: 52, category: 'Beauty', description: 'Science facts' },
    { id: 136, name: 'Wifi Extender', imageUrl: 'https://picsum.photos/id/151/200/300', price: 44, category: 'Garden', description: 'Range booster' },
    { id: 137, name: 'Sweatpants', imageUrl: 'https://picsum.photos/id/152/200/300', price: 40, category: 'Sports', description: 'Comfy sweatpants' },
    { id: 138, name: 'Atlas for Kids', imageUrl: 'https://picsum.photos/id/153/200/300', price: 25, category: 'Home', description: 'Child-friendly atlas' },
    { id: 139, name: 'Smart Bulb', imageUrl: 'https://picsum.photos/id/154/200/300', price: 33, category: 'Office', description: 'Remote control bulb' },
    { id: 140, name: 'Midi Dress', imageUrl: 'https://picsum.photos/id/155/200/300', price: 96, category: 'Automotive', description: 'Stylish midi dress' },
    { id: 141, name: 'Science Stories', imageUrl: 'https://picsum.photos/id/156/200/300', price: 24, category: 'Health', description: 'Fun science tales' },
    { id: 142, name: 'Microphone', imageUrl: 'https://picsum.photos/id/157/200/300', price: 79, category: 'Books', description: 'Recording mic' },
    { id: 143, name: 'Swimsuit', imageUrl: 'https://picsum.photos/id/158/200/300', price: 52, category: 'Clothing', description: 'Swimwear' },
    { id: 144, name: 'Travel Book', imageUrl: 'https://picsum.photos/id/159/200/300', price: 35, category: 'Electronics', description: 'Travel adventures' },
    { id: 145, name: 'Fitness Tracker', imageUrl: 'https://picsum.photos/id/160/200/300', price: 99, category: 'Toys', description: 'Steps and health' },
    { id: 146, name: 'Parka', imageUrl: 'https://picsum.photos/id/161/200/300', price: 175, category: 'Beauty', description: 'Thick winter parka' },
    { id: 147, name: 'Fairy Tales', imageUrl: 'https://picsum.photos/id/162/200/300', price: 23, category: 'Garden', description: 'Tales for kids' },
    { id: 148, name: 'USB Hub', imageUrl: 'https://picsum.photos/id/163/200/300', price: 40, category: 'Sports', description: 'Multiport hub' },
    { id: 149, name: 'Sweatshirt', imageUrl: 'https://picsum.photos/id/164/200/300', price: 53, category: 'Home', description: 'Cozy sweatshirt' },
    { id: 150, name: 'Novella', imageUrl: 'https://picsum.photos/id/165/200/300', price: 19, category: 'Office', description: 'Short novel' },
    { id: 151, name: 'Webcam', imageUrl: 'https://picsum.photos/id/166/200/300', price: 62, category: 'Automotive', description: 'Video webcam' },
    { id: 152, name: 'Beanie', imageUrl: 'https://picsum.photos/id/167/200/300', price: 17, category: 'Health', description: 'Warm beanie' },
    { id: 153, name: 'Cooking for Kids', imageUrl: 'https://picsum.photos/id/168/200/300', price: 30, category: 'Books', description: 'Kids recipes' },
    { id: 154, name: 'Dash Cam', imageUrl: 'https://picsum.photos/id/169/200/300', price: 110, category: 'Clothing', description: 'Car camera' },
    { id: 155, name: 'Pullover', imageUrl: 'https://picsum.photos/id/170/200/300', price: 61, category: 'Electronics', description: 'Stylish pullover' },
    { id: 156, name: 'Music Theory Book', imageUrl: 'https://picsum.photos/id/171/200/300', price: 38, category: 'Toys', description: 'Learn music theory' },
    { id: 157, name: 'Monitor Stand', imageUrl: 'https://picsum.photos/id/172/200/300', price: 48, category: 'Beauty', description: 'Desk stand' },
    { id: 158, name: 'Dress Pants', imageUrl: 'https://picsum.photos/id/173/200/300', price: 80, category: 'Garden', description: 'Formal pants' },
    { id: 159, name: 'Biography 3', imageUrl: 'https://picsum.photos/id/174/200/300', price: 27, category: 'Sports', description: 'Another life story' },
    { id: 160, name: 'Streaming Box', imageUrl: 'https://picsum.photos/id/175/200/300', price: 120, category: 'Home', description: 'TV box' },
    { id: 161, name: 'Graphic Tee', imageUrl: 'https://picsum.photos/id/176/200/300', price: 35, category: 'Office', description: 'Printed T-shirt' },
    { id: 162, name: 'Science Encyclopedia', imageUrl: 'https://picsum.photos/id/177/200/300', price: 61, category: 'Automotive', description: 'In-depth science' },
    { id: 163, name: 'Smart Switch', imageUrl: 'https://picsum.photos/id/178/200/300', price: 38, category: 'Health', description: 'Control switch' },
    { id: 164, name: 'Flannel Shirt', imageUrl: 'https://picsum.photos/id/179/200/300', price: 47, category: 'Books', description: 'Check flannel' },
    { id: 165, name: 'History Stories', imageUrl: 'https://picsum.photos/id/180/200/300', price: 21, category: 'Clothing', description: 'Past events' },
    { id: 166, name: 'Fitness Rope', imageUrl: 'https://picsum.photos/id/181/200/300', price: 29, category: 'Electronics', description: 'Smart skipping rope' },
    { id: 167, name: 'Polo Dress', imageUrl: 'https://picsum.photos/id/182/200/300', price: 90, category: 'Toys', description: 'Sporty dress' },
    { id: 168, name: 'Activity Book', imageUrl: 'https://picsum.photos/id/183/200/300', price: 19, category: 'Beauty', description: 'For kids activities' },
]